### ISSUE TITLE
cv2.cv.CV_XYZ2BGR instead of cv2.CV_XYZ2BGR

### ISSUE THREAD

**Issue by SreeniASU** [SreeniASU/multimedia-information-systems#11]
@jakepruitt 

 For Part1 code, in colors2image.py I guess, cv2.CV_XYZ2BGR won't work. It has to be cv2.cv.CV_XYZ2BGR. Similarly for others. I have made the fix in my system and then it worked perfectly fine. Can you please check that?

**Comment by jakepruitt** [comment]
Jumping on this now, looks like using XYZ isn't working at all at the moment. Going to work on this for a few hours, try to get test cases set up for all color spaces, and possibly add a few more checks to the input to accept different ranges depending on the color space. @SreeniASU are you online right now?

**Comment by jakepruitt** [comment]
This has been fixed
