### ISSUE TITLE
Second Part assumes BGR

### ISSUE THREAD

**Issue by jakepruitt** [SreeniASU/multimedia-information-systems#12]
At the moment, part 2 still assumes that the color map is BGR. Should this allow for different colorspaces?

cc/ @Perryo @GCrispino @ApertureTS

**Comment by GCrispino** [comment]
I don't really know if that is necessary. But if we do that, wouldn't we have to only use that cvtColor function? Am I right? 
Em 19/09/2015 2:05 PM, Jake Pruitt notifications@github.com escreveu:At the moment, part 2 still assumes that the color map is BGR. Should this allow for different colorspaces?

cc/ @Perryo @GCrispino @ApertureTS

**Comment by Perryo** [comment]
The color map is not a specific color space so I don't think it will matter
