### ISSUE TITLE
Project Demo

### ISSUE THREAD

**Issue by ApertureTS** [SreeniASU/multimedia-information-systems#16]
Wed 9/23 from 4-4:30 pm. this time seems to work best with everyone's schedules.

I didn't see when Sreenivas was availible on Wed. We will need a laptop that can run our project. 

![image](https://cloud.githubusercontent.com/assets/9064846/9983776/c81b5c42-5fbe-11e5-9814-52719dcbc788.png)

**Comment by jakepruitt** [comment]
Sweet, thanks for setting this up @ApertureTS. I will be sure to be there.

**Comment by SreeniASU** [comment]
Hi,

 I will be there at 4.

Thanks
Sreenivas

On Sun, Sep 20, 2015 at 6:57 PM, Jake Pruitt notifications@github.com
wrote:

> Sweet, thanks for setting this up @ApertureTS
> https://github.com/ApertureTS. I will be sure to be there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/16#issuecomment-141855135
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by GCrispino** [comment]
Have I been assigned to this? I don't know if I will be able to go, because I have class at 4:30 pm, but if nobody can go, maybe I can do it.

**Comment by Perryo** [comment]
I can make it however I do not have this set up on my laptop

**Comment by ApertureTS** [comment]
Just so you all know the project is submitted.
Also, we don't need for everyone to be there, but as many as possible (he
said at least 2 people). I was hoping Jake could bring his? If not, or no
one else can, I have an older one that boots to Linux. I don't like to
bring it because its heavy.

**Comment by GCrispino** [comment]
@ApertureTS, you only have this old one? It doesn't have to have linux installed linux, it only has to have python and opencv-Python installed on it.

**Comment by jakepruitt** [comment]
@ApertureTS I just remembered that I have a test tomorrow in my 3:00 class, which means I have to attend. Any other day I would skip and be able to make the demo. I'll try to get done with the test early and get over to the demo as soon as I can, but someone else will need to be prepared to demo on their own laptop. Sorry guys.

**Comment by ApertureTS** [comment]
I'll try to install everything tonight to make sure it works.
Jake,  it's fine. As long as we have someone who worked on easy part,  we
should be ok.

**Comment by Perryo** [comment]
Who all is going to this? I've got to come from a physical therapy session in Chandler so I may be cutting it very close. If it is the case that I need to attend, I also need to set this up on my laptop.

**Comment by ApertureTS** [comment]
I'll be there.  And I have my laptop.

**Comment by SreeniASU** [comment]
I shall also join. Sorry for not replying for the past two-three days as I
was not feeling well with my health.

On Wed, Sep 23, 2015 at 9:51 AM, ApertureTS notifications@github.com
wrote:

> I'll be there. And I have my laptop.
> On Sep 23, 2015 8:19 AM, "James" notifications@github.com wrote:
> 
> > Who all is going to this? I've got to come from a physical therapy
> > session
> > in Chandler so I may be cutting it very close. If it is the case that I
> > need to attend, I also need to set this up on my laptop.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/SreeniASU/multimedia-information-systems/issues/16#issuecomment-142637130
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/16#issuecomment-142660017
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by GCrispino** [comment]
I'll go too. I am bringing my laptop(its battery is not so good, but I am bringing its charger as well).
