### ISSUE TITLE
Demo Review

### ISSUE THREAD

**Issue by jakepruitt** [SreeniASU/multimedia-information-systems#17]
Today we had our demo with the TA, which provided a lot of feedback and clarified the requirements of the assignment much more. Here are the notes I can remember from the meeting:
#### How did we do color conversions?

We answered by saying that we converted colors using `cv2.cvtColor` native library with OpenCV, which seemed to be sufficient. This bit us later down the road when we said we didn't implement YUV because there was no conversion to or from that colorspace in OpenCV. It is obvious that the TA wants all of the colorspaces listed in the project description to be implemented, whether or not OpenCV has built-in support. It was also clear that the TA wants a deep dive into the way color transformations take place in the research paper. The two big deliverables that resulted from this are:
- **Implement all color spaces specified in class**
- **Describe formulas for color conversions in the paper** (formulas described [here](http://docs.opencv.org/modules/imgproc/doc/miscellaneous_transformations.html?highlight=cvtcolor#cvtcolor))
#### Robust handling of different inputs for color conversion

The primary hole in the colormap creation was the broken output for trying to make red to yellow to green in XYZ. The output was not the expected output, meaning that we need more test cases for the first part. This may possibly be resolved by doing the color conversions ourselves, just so we aren't relying on OpenCV for doing everything. The two main things we can do to improve this are:
- **More tests for colormap** - I already have a test framework set up for ensuring the right inputs produce the expected outputs in part one. There are some tests that are still failing in that part, so we need more eyes and many more tests.
- **Implementation of missing color spaces** - we will need to write custom functions for converting to the missing color spaces.
#### Methodology for selecting representative colors

We didn't do a good job at answering this question, and I think the report probably deserves some improvements on describing how the 2<sup>b</sup> colors are chosen. I suspect that there may also be issues in the way we are partitioning when the input has floating point numbers rather than integers. We have tests cases set up for this part of the functionality, so we will need more robust tests, a solid explanation of our choice, and example output in the paper.
- **More tests for partitioning function** - we need integer and floating point tests
- **Paper explanations** - There should be an example output in the paper of the colormap text file
#### General improvements to first part implementation

There should be a way for users to specify the output file, or randomly generate the name of the PNG output. I think there was another improvement to the input that I can't remember.
#### Proof of functionality of second part

This is a really difficult thing to test, but it would be nice to have a video file with two frames, one black, one white, and just confirm how we expect our output to work. The TA seemed skeptical, and also questioned our understanding of absolute vs. relative differences. The two things I think could be done for the second part are
- **Possibly an automated test that handles a very simplified video**
- **More explanation in the paper about absolute or relative differences**
#### More information in report

The TA was asking for more information in the report than we were expecting, specifically around getting the code set up to run and color conversion descriptions.

If you have any input or want to take on some of these tasks, go ahead and comment here, and get ready to work on it as soon as possible. @ApertureTS said he would move the report to a google doc for easier collaboration, so let us know what the status is for that.

cc/ @Perryo @GCrispino @SreeniASU

**Comment by ApertureTS** [comment]
the report is on drive. I will also add the step-by-step instructions on using the program to the report

**Comment by SreeniASU** [comment]
I will be looking into the XYZ issue from tmrw morning..

On Thu, Sep 24, 2015 at 6:24 PM, ApertureTS notifications@github.com
wrote:

> the report is on drive. I will also add the step-by-step instructions on
> using the program to the report
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/17#issuecomment-143097156
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by SreeniASU** [comment]
Is anyone in? ;) XYZ is working fine in my system now after the fix.. If
all of you can have a look it would be great. :)

On Fri, Sep 25, 2015 at 11:18 PM, Sreenivas Shenoy spsheno1@asu.edu wrote:

> I will be looking into the XYZ issue from tmrw morning..
> 
> On Thu, Sep 24, 2015 at 6:24 PM, ApertureTS notifications@github.com
> wrote:
> 
> > the report is on drive. I will also add the step-by-step instructions on
> > using the program to the report
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/SreeniASU/multimedia-information-systems/issues/17#issuecomment-143097156
> > .
> 
> ## 
> 
> Sreenivas P Shenoy
> M.S. Computer Science & Engineering
> Arizona State University,
> spsheno1@asu.edu
> Cell 480-738-3280

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by ApertureTS** [comment]
Nice. I added instructions on using our project.

**Comment by jakepruitt** [comment]
@SreeniASU what fix did you make?

**Comment by SreeniASU** [comment]
The colormap image was getting properly saved. Just that it has a display
issue. What I did was instead of directly displaying the colormap on the
fly, I save the colormap file, and then read the file and display it. It
worked in my system after that. Can you please check if that is working
fine in your system?

Thanks
Sreenivas

On Sun, Sep 27, 2015 at 3:54 PM, Jake Pruitt notifications@github.com
wrote:

> @SreeniASU https://github.com/SreeniASU what fix did you make?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/17#issuecomment-143599912
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by SreeniASU** [comment]
Attached is one XYZ colormap file.

[image: Inline image 1]

On Sun, Sep 27, 2015 at 4:00 PM, Sreenivas Shenoy spsheno1@asu.edu wrote:

> The colormap image was getting properly saved. Just that it has a display
> issue. What I did was instead of directly displaying the colormap on the
> fly, I save the colormap file, and then read the file and display it. It
> worked in my system after that. Can you please check if that is working
> fine in your system?
> 
> Thanks
> Sreenivas
> 
> On Sun, Sep 27, 2015 at 3:54 PM, Jake Pruitt notifications@github.com
> wrote:
> 
> > @SreeniASU https://github.com/SreeniASU what fix did you make?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/SreeniASU/multimedia-information-systems/issues/17#issuecomment-143599912
> > .
> 
> ## 
> 
> Sreenivas P Shenoy
> M.S. Computer Science & Engineering
> Arizona State University,
> spsheno1@asu.edu
> Cell 480-738-3280

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by ApertureTS** [comment]
https://docs.google.com/a/asu.edu/document/d/14waJr3Hi4qJ6Vno1A5laBM19xrLSMOvwpyxMBH1hPd4/edit?usp=sharing

**Comment by jakepruitt** [comment]
@SreeniASU I will go ahead and add the code for saving, opening, and displaying the color into the project. Thanks @ApertureTS for sharing that. What is our current feeling on the other deliverables for the final submittal? I am willing to jump on these tasks:
- **Add code for fixing XYZ**

**Comment by jakepruitt** [comment]
As well as the following tasks:
- More tests for part 1
- In-depth description of color models
- Possibly adding other color models to part 1

Things that I could use help with:
- Allowing different color models in part 2
- Possibly more tests in part 2
- In-depth explanation for choosing representative samples of color partitions

**Comment by SreeniASU** [comment]
Jake, As of now XYZ is working in my system. Can you please check with the
latest code in git? I have attached  a file as well for the colormap file
in the previous mail. I need to go out and will come back by 8 and will
work.

On Sun, Sep 27, 2015 at 4:09 PM, Jake Pruitt notifications@github.com
wrote:

> As well as the following tasks:
> - More tests for part 1
> - In-depth description of color models
> - Possibly adding other color models to part 1
> 
> Things that I could use help with:
> - Allowing different color models in part 2
> - Possibly more tests in part 2
> - In-depth explanation for choosing representative samples of color
>   partitions
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/17#issuecomment-143602061
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by jakepruitt** [comment]
> Can you please check with the latest code in git?

@SreeniASU I don't see that you've made any changes to the git codebase, do you want me to make the changes and contribute to the codebase. And as for the attached image, it did not go through on the email, could you attach it in a github comment on this issue?

> As of now XYZ is working in my system

In the future, could you write a test case that proves that this functionality is working on your system?

**Comment by SreeniASU** [comment]
Oops.. Wasn't there a new PR? let me check. Am sorry.

On Sun, Sep 27, 2015 at 4:24 PM, Jake Pruitt notifications@github.com
wrote:

> Can you please check with the latest code in git?
> 
> @SreeniASU https://github.com/SreeniASU I don't see that you've made
> any changes to the git codebase, do you want me to make the changes and
> contribute to the codebase. And as for the attached image, it did not go
> through on the email, could you attach it in a github comment on this issue?
> 
> As of now XYZ is working in my system
> 
> In the future, could you write a test case that proves that this
> functionality is working on your system?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/17#issuecomment-143602743
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by Perryo** [comment]
Sorry guys ive been out all day, and getting a new phone so i've been hard to contact. I saw Derek sent an invite for a chat, how is everything going? Do you guys need help?

**Comment by jakepruitt** [comment]
Hey @Perryo we just finished up the report and resubmitted it to the TA. Check out the final version at the google doc link that @ApertureTS posted above. Thanks for checking in, and don't worry about having things come up, there will be plenty more work in the future.
