### ISSUE TITLE
Part 2 Task 2 - Spatial Predictive Encoding

### ISSUE THREAD

**Issue by jakepruitt** [SreeniASU/multimedia-information-systems#19]
The second task of part 2 of running predictive encoding algorithms A, B, C and the combination of all of them can be done independently of task 1. After chatting with @SreeniASU, he said he would be available to tackle this around Thursday night. @GCrispino and @ApertureTS, if you are available to work with him on it, let him know.

**Comment by ApertureTS** [comment]
Thur I should be free most of the evening. Nice job everyone.

**Comment by Perryo** [comment]
We finished encoding options 1,2,and 3 for part 1 last night. I also pushed some changes that write these errors to a file in the format of 
< f#, (x,y), e >  
where f# is the frame number, x,y is the pixel location, and e is the error. It also properly names the file according to the video and option selected.

**Comment by GCrispino** [comment]
Did you guys figure out what those alpha values meant on the last predictor option?

**Comment by jakepruitt** [comment]
@SreeniASU just a question, we keep all of the alpha values at 1/3 for the spatial encoding option 5, while the report says these values should adjust dynamically. Was this the extra credit the professor was talking about?

**Comment by SreeniASU** [comment]
Yes. I tried that, but it doesn't seem to work.

On Sun, Nov 1, 2015 at 3:11 PM, Jake Pruitt notifications@github.com
wrote:

> @SreeniASU https://github.com/SreeniASU just a question, we keep all of
> the alpha values at 1/3 for the spatial encoding option 5, while the report
> says these values should adjust dynamically. Was this the extra credit the
> professor was talking about?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/19#issuecomment-152869318
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280
