### ISSUE TITLE
Project 2 - Report

### ISSUE THREAD

**Issue by Perryo** [SreeniASU/multimedia-information-systems#23]
Hey guys, I think everyone should take a look at the report Sreenivas started and add information for what they worked on. I have just updated it with how part 3 quantization works. 

https://docs.google.com/document/d/1ipwWj7_L2Lo2YyALkra3Vl_dNu2RePTktVzG0QuPnFg/edit?ts=563159c6

**Comment by jakepruitt** [comment]
@Perryo I just updated the report, if you could take a look. I know that you wanted to format it specifically with Microsoft Word:tm:, so if you want to do that and then officially submit it when you get the chance, I'm happy with where it is.

**Comment by Perryo** [comment]
Will do, ill send you guys the doc file once i finish updating it.
