### ISSUE TITLE
Project 3 - Task Splitting

### ISSUE THREAD

**Issue by Perryo** [SreeniASU/multimedia-information-systems#30]
Hey guys, I think we should all meet this week, maybe tomorrow, and talk about Part 3, the due date is going to sneak up on us and its around thanksgiving which may prove problematic for some people. Is everyone okay with meeting tomorrow? I will be available after 4pm.

**Comment by GCrispino** [comment]
Tomorrow would be fine for me if everybody is available.

**Comment by SreeniASU** [comment]
Fine with me too

On Mon, Nov 9, 2015 at 10:42 PM, GCrispino notifications@github.com wrote:

> Tomorrow would be fine for me if everybody is available.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-155300104
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by Perryo** [comment]
Lets plan on meeting around 5:30?

https://hangouts.google.com/call/6ab3jj3nmkbbcerfslrnacvsfqa

**Comment by SreeniASU** [comment]
Sure!!

On Tue, Nov 10, 2015 at 3:59 PM, James notifications@github.com wrote:

> Lets plan on meeting around 5:30?
> 
> https://hangouts.google.com/call/6ab3jj3nmkbbcerfslrnacvsfqa
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-155594880
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by Perryo** [comment]
# Please finish your part by Nov 17th.

Jake and Derek, here is what we have decided in the group meeting. 
Part 1 (c) and Part 2 are both open and very similar, if you would like to work on them together that would be fine, you can also do them separately. We are aiming to have these done in the next week so that we can start part 3 and be done with ample time before the deadline. 
Also, please fill out the section of the report for your part, Sreenivas will be posting the google hangout links soon.
Task 1(a) - James 
Task 1(b) - Sreenivas
Task 1(c) - Jake
Task 1(d) - Gabriel
Task 2 -
Task 3 - We will all convene and work on this together

Let us know if you have any concerns.
Thanks!

**Comment by SreeniASU** [comment]
What a wonderful explanation of Discrete Cosine Transform :)

https://www.youtube.com/watch?v=Q2aEzeMDHMA

On Tue, Nov 10, 2015 at 5:49 PM, James notifications@github.com wrote:

> Please finish your part by Nov 17th.
> 
> Jake and Derek, here is what we have decided in the group meeting.
> Part 1 (c) and Part 2 are both open and very similar, if you would like to
> work on them together that would be fine, you can also do them separately.
> We are aiming to have these done in the next week so that we can start part
> 3 and be done with ample time before the deadline.
> Also, please fill out the section of the report for your part, Sreenivas
> will be posting the google hangout links soon.
> Task 1(a) - James
> Task 1(b) - Sreenivas
> Task 1(c) -
> Task 1(d) - Gabriel
> Task 2 -
> Task 3 - We will all convene and work on this together
> 
> Let us know if you have any concerns.
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-155615579
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by jakepruitt** [comment]
Hey, sorry I didn't see this sooner, I don't get mail unless I'm specifically mentioned. Task 1(c) sounds good for me, and once that's done extrapolating to task 2 shouldn't be that tough. Updated the comment above :shipit: Will get this moving tonight.

**Comment by Perryo** [comment]
@jakepruitt @GCrispino @SreeniASU @ApertureTS 
Hey guys, I want to check my understanding for Part 1, because I'm scared of the possibility for very large data issues as we had last project. 

The requirements state that we will split each frame into 8x8 regions called _frameblocks_. Then, at least for part a, we work on every block in _every frame_. So this means:

**Assumption 1:**
1. We quantize each block in every frame individually.
2. Variance is very small, 64 pixel sample size is not very large and they are spatially _very_ close which may mean a lot of the values are similar.
3. This is a TON of processing, if a given video is 480p with 4:3 aspect ratio and 1000 frames (a very conservative assumption) this means each frame will have 640x480 pixels.
- 4800 8x8 regions per frame
- 4,800,000 regions total, therefore we have to quantize data **4.8 million times**. Resulting in a histogram that I personally would never want to see.

**Assumption 2:**
1. We scan the video once, find the min and max values, and create _m_ bins for quantizing
2. Then break each frame into 8x8 blocks and quantize all those values using the bin we created.
However, I feel this method defeats the purpose of creating an 8x8 region in the first place, as processing the frame in that manner doesn't add or remove any functionality if we are quantizing the video as a whole. 

Let me know what you guys think, I think I've sufficiently confused myself.

**Comment by jakepruitt** [comment]
My reading of part 1 is more in line with Assumption 2, where we quantize with the whole video.

> and create m bins for quantizing

Rather than _m_ bins, I think we are getting the user-supplied _n_ bins for quantizing.

> quantize all those values using the bin we created.

I think the clue here is the format of the output of 1(c):

> ( frame_id, block_coord, gray_instance_id, num_pixels )

I think we quantize every pixel in a block, and output the **count** of each quantized value in a block. Thus an example would be:

```
...
< 1, (8, 8), 156, 3 >
< 1, (8, 8), 124, 35 >
< 1, (8, 8), 92, 6 >
...
< 2, (16, 16), 156, 2 >
< 2, (16, 16), 124, 7 >
< 2, (16, 16), 92, 22 >
...
```

Where 1 is the first frame, (8,8) is the top-left coordinate of the frame-block, and each frame-bock will have all _n_ grey color instances (represented by one integer 0-256), and a count for the number of pixels in that frame that relate to that quantized value.

@Perryo how does that sound?

**Comment by Perryo** [comment]
@jakepruitt 

That makes sense, in your example, the value (8,8) corresponds to the region and not necessarily the pixel location, are we losing this information in this quantization process?

**Comment by jakepruitt** [comment]
@Perryo yes, I think the goal is to aggregate and simplify the image data with the hope of comparing frames of a video. Here, we're effectively getting an histogram of the frequency of each quantized grey in each 8x8 region. During the final step, we will find the most common frames by comparing these histograms, which is more effective and fast than comparing individual pixels.

**Comment by ApertureTS** [comment]
Regions containing many pixels makes sense.
for the last step, how would we comparing the blocks? just read the file
created and compare what we wrote to the file? Is there a set way to score
how well they match?

**Comment by GCrispino** [comment]
@Perryo , I thought that we have to do something like Assumption 1, but what you said about large amounts of data and what @jakepruitt said about Assumption 2 make sense. I am concerned about this because task 1-d(that I have to do) is similar to task 1-a, so it is important we understand what they are asking us(what can be pretty confusing sometimes).

So, about the last component on the output(numpixels on task 1-a and pixelcount os task 1-b): do you guys think it should be the count for how many pixels on the block have the same value on the Y color space?

**Comment by Perryo** [comment]
@GCrispino Yes, I think that we count the occurrence of those values and store that, if you want to see an example of this my code has been checked in, look for _occurancesInFrame_. Also @jakepruitt Yash responded to my email question, and it appears he wants quantization at the block level, however I have implemented the rest the way you specified as that makes the most sense. I'm currently working on a way to find the coordinates as the way I am dividing the regions doesn't allow me to find this.

**Comment by GCrispino** [comment]
@Perryo So, should we quantize each block individually, since Yash said so? Or are you just going to do it the other you since you have already started?

**Comment by GCrispino** [comment]
(sorry, I closed the issue by mistake)

**Comment by jakepruitt** [comment]
@Perryo could you reply to yash asking why we have the number_pixels in the data?

**Comment by Perryo** [comment]
@GCrispino That is my understanding, Yash said that is what is expected. @jakepruitt I can email him and ask, but I believe it is used to construct the histogram as it is important to know the number of occurrences for each value.

**Comment by GCrispino** [comment]
@Perryo ok. So I think we should stick with working with the blocks individually, since Yash said that. I have been doing some early tests for my part and it is already taking some time. Maybe that is the way it is.

**Comment by Perryo** [comment]
@GCrispino @jakepruitt 
Hey guys, I have the majority of my part done (still have to make histogram) but I've done the part that quantized each region and I am having the exact issue I was afraid of; It takes an extremely long time to process all this information.
1. Each video has around 700+ frames
2. Each frame has 4800 regions
3. Each region has 64 pixles: 64 \* 4800 \* 700 = **_215,040,000_** calculations

I've been running while I typed this and I'm at about frame 20....
I'll check in my code maybe you guys can look at it?

**Comment by jakepruitt** [comment]
Keeping you all in the loop, I just sent Yash a quick clarification question, here's what I asked:

---

I just had a quick clarification for Task 1(c). First, I want to make sure I am using the correct wavelet filter: I am working under the assumption that we are applying the 2D Haar transform to each block in each frame. Is this correct, or should we be using a different wavelet transform like Daubechies, Antonini, Villa, or Brislawn?

Second, I am assuming that we want to apply a three-stage wavelet transform, producing a matrix like the following:

<img width="250" alt="screenshot 2015-11-15 15 29 19" src="https://cloud.githubusercontent.com/assets/5084263/11171516/552d3c1a-8baf-11e5-8c8c-e526657a00aa.png">

Is this correct, or should we only be applying one-stage wavelet transform?

Now, given the result of three-stage wavelet transform above, you specify we should output the n most significant wavelet components. I am operating under the assumption that we should sort the components above by their magnitude ( |x| ), and take the n largest magnitude components. Thus, for n=5, the components that would be kept are {57, 39, -37, 33, -33}. Each of these would be identified by the level of transformation and coordinates within that block (e.x. the top-left cell of -57 is LL300, which would be in the 3rd level transform LL block at x=0, y=0). Thus, the output would be

< frame_id, block_coord, LL300, -57 >
< frame_id, block_coord, HL200, 39 >
< frame_id, block_coord, HL300, -37 >
< frame_id, block_coord, HL211, 33 >
< frame_id, block_coord, LH102, -33 >

Is this correct?

**Comment by GCrispino** [comment]
@Perryo , were you able to finish the program? Also, since in my assigned task I also have to do quantizing, but for the differences of the frames on the blocks, do yo think it would be adequate to use your code(I am assuming you used the same code from task 3 of project 2, didn't you?), since it is basically the same thing?

**Comment by Perryo** [comment]
@GCrispino 
I did (still need to do histogram), but I had to change around a bit of the quantization, but you should be fine using my solution. Would you try and run mine on your machine? My VM actually ran out of memory before it could finish...

**Comment by GCrispino** [comment]
@Perryo oh, I see. I could try to run it here. I am getting some memory issues here with some of the sample videos as well.

**Comment by GCrispino** [comment]
@Perryo , I ran your code and it generated a .mp4 file with a size of 1.05 GB. I opened in a text editor and its formatting, at least, seems allright.

![multimedia_project3_task1a](https://cloud.githubusercontent.com/assets/8827509/11174018/621260f0-8bdb-11e5-984f-d4248699ed35.PNG)

**Comment by Perryo** [comment]
@GCrispino  
Thanks for checking that but....
1.5 gb!!!!! That is not okay, I need to talk with Yash. Also I forgot to name the file correctly, but that shouldnt be a big deal. The main concern I have is this data still needs to be interpreted for the histogram...

**Comment by GCrispino** [comment]
@Perryo 
Yeah man, I can see that large amounts of data are going to be a big concern on this project.

**Comment by Perryo** [comment]
@GCrispino @SreeniASU @jakepruitt @ApertureTS 
Hey guys, can we all meet around 7:00pm today to discuss what we have accomplished?

**Comment by ApertureTS** [comment]
sure, I have another group chat at 7:30, so I can only be on for 30 min

**Comment by SreeniASU** [comment]
Sure!!

On Tue, Nov 17, 2015 at 2:59 PM, Derek notifications@github.com wrote:

> sure, I have another group chat at 7:30, so I can only be on for 30 min
> 
> On Tue, Nov 17, 2015 at 2:02 PM, James notifications@github.com wrote:
> 
> > @GCrispino https://github.com/GCrispino @SreeniASU
> > https://github.com/SreeniASU @jakepruitt <
> > https://github.com/jakepruitt>
> > @ApertureTS https://github.com/ApertureTS
> > Hey guys, can we all meet around 7:00pm today to discuss what we have
> > accomplished?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-157506497
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-157522531
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by jakepruitt** [comment]
Sounds good.

**Comment by Perryo** [comment]
https://hangouts.google.com/call/6ab3jj3nmkbbcerfslrnacvsfqa

**Comment by GCrispino** [comment]
Hey guys, just for your information: in case you don't know, earlier today the TA posted some new videos that have a smaller resolution(only 64x64 - YAY). So, I have just commited some changes to my code and put those new videos on the test/project1 folder as well.

**Comment by Perryo** [comment]
@GCrispino @jakepruitt 
Just a heads up, i've tried different methods including ensuring types are float until the final value is calculated for quantization and still have not found a solution. It appears its capable of falling off both ends of the range, where it can calculate a value less than and greater than the min and max of the region respectively.

**Comment by jakepruitt** [comment]
@Perryo @GCrispino I have some bandwidth to hop on this rounding issue tonight.

@SreeniASU how's the DCT going? If you get a chance, could you push what you have so we can give it a review?

@ApertureTS Did you get any time to start task 2? Yash has pretty definitively answered the question about rectangular frames by saying "All frames are 64x64". We can probably build out whole video DWT now with very little change to Task 1c code. If you don't have time to write this out and push it up, I can run it out tonight.

**Comment by SreeniASU** [comment]
Hello Jake,

 I have pushed the latest code and the code works perfectly fine. I have
done DCT implementation in two ways.

1) FindDCT method is the naive implementation of DCT formula. Apparently
performance is very low.

2) FindDCTFast method computes DCT in ultra - fast way. ;)  But I would
like to stick upon to the method FindDCT as it is more readable and is
direct implementation of the formula.

Would like to get it reviewed from you people.

Thanks
Sreenivas

On Fri, Nov 20, 2015 at 3:44 PM, Jake Pruitt notifications@github.com
wrote:

> @Perryo https://github.com/Perryo @GCrispino
> https://github.com/GCrispino I have some bandwidth to hop on this
> rounding issue tonight.
> 
> @SreeniASU https://github.com/SreeniASU how's the DCT going? If you get
> a chance, could you push what you have so we can give it a review?
> 
> @ApertureTS https://github.com/ApertureTS Did you get any time to start
> task 2? Yash has pretty definitively answered the question about
> rectangular frames by saying "All frames are 64x64". We can probably build
> out whole video DWT now with very little change to Task 1c code. If you
> don't have time to write this out and push it up, I can run it out tonight.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-158547060
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by ApertureTS** [comment]
I started task 2,  plan on working more tonight and tomorrow morning.
Did we decide on the Id?

**Comment by GCrispino** [comment]
@jakepruitt cool. If you have any updates on it please let me know.
@Perryo about the histogram, I think we may have an issue. Last class I asked the professor about how the "pixelcount" value on the output of task 1d. I didn't understand too much his answer, but he said something about showing the histogram for a certain region of pixels or pixel values, which I believe that is different from what both of us are doing right now. Also, he mentioned that the "n" is related with the histogram, and not with the quantization.

So, I think that maybe going to the TA's office hours to clarify everything should be a good idea, since, as we have talked about, get answers by email might not be the best solution.

**Comment by Perryo** [comment]
@GCrispino @SreeniASU @jakepruitt @ApertureTS 

Lets meet around noon today if possible.

https://hangouts.google.com/call/vjw4qbimspyec4335z32evcq2ma

**Comment by GCrispino** [comment]
@Perryo thats fine for me. I would like to leave around 1 or 1:15 because of the ASU game, if that's ok for you guys.

**Comment by ApertureTS** [comment]
I have something at 1230, but I can be on for 30 min

**Comment by SreeniASU** [comment]
So, At what time are we meeting?

On Sat, Nov 21, 2015 at 10:46 AM, Derek notifications@github.com wrote:

> I have something at 1230, but I can be on for 30 min
> On Nov 21, 2015 10:43 AM, "GCrispino" notifications@github.com wrote:
> 
> > @Perryo https://github.com/Perryo thats fine for me. I would like to
> > leave around 1 or 1:15 because of the ASU game, if that's ok for you
> > guys.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-158664615
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-158664862
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by jakepruitt** [comment]
@SreeniASU 12:00

**Comment by GCrispino** [comment]
@SreeniASU actually we have already started

**Comment by SreeniASU** [comment]
Please post the link

On Sat, Nov 21, 2015 at 12:02 PM, GCrispino notifications@github.com
wrote:

> @SreeniASU https://github.com/SreeniASU actually we have already started
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-158672629
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by jakepruitt** [comment]
https://hangouts.google.com/call/vjw4qbimspyec4335z32evcq2ma

**Comment by jakepruitt** [comment]
Just had a chat with Yash, have some good feedback to move forward with.
1. The quantization with block-level max and min is correct
2. When talking about the histogram, Yash said it would be better to show the 64 histograms of each frame, rather than a histogram of the entire video. However, both of these features are more than required and "Extra features do not take points off."
3. When choosing the "most significant" wavelets for DCT and DWT, I think we may need to rethink the way we choose those most significant wavelets. Yash was vague, but says there is a "right way" to do this, which makes me suspect we're doing it wrong. @SreeniASU I may need to circle back with you and change how we choose what is the most significant, possibly following the JPEG zig-zag standard.
4. The diff algorithm for histogram data needs to be a bit different than what it is now. While right now we compare the _count_ in each quanta to the count in the same quanta in a different frame block, we need to compare the _shape_ of each histogram. @Perryo could you look up different ways to compare histograms?

Other than the usual grouchiness, tendency to be abrasive, and persistence in punching holes in every word you say, Yash was a pleasure to meet with. Any questions moving forward?

**Comment by SreeniASU** [comment]
Cool. I will start looking into how to find the most significant DCT
components today late night.

On Mon, Nov 23, 2015 at 3:13 PM, Jake Pruitt notifications@github.com
wrote:

> Just had a chat with Yash, have some good feedback to move forward with.
> 1. The quantization with block-level max and min is correct
> 2. When talking about the histogram, Yash said it would be better to
>    show the 64 histograms of each frame, rather than a histogram of the entire
>    video. However, both of these features are more than required and "Extra
>    features do not take points off."
> 3. When choosing the "most significant" wavelets for DCT and DWT, I
>    think we may need to rethink the way we choose those most significant
>    wavelets. Yash was vague, but says there is a "right way" to do this, which
>    makes me suspect we're doing it wrong. @SreeniASU
>    https://github.com/SreeniASU I may need to circle back with you and
>    change how we choose what is the most significant, possibly following the
>    JPEG zig-zag standard.
> 4. The diff algorithm for histogram data needs to be a bit different
>    than what it is now. While right now we compare the _count_ in each
>    quanta to the count in the same quanta in a different frame block, we need
>    to compare the _shape_ of each histogram. @Perryo
>    https://github.com/Perryo could you look up different ways to
>    compare histograms?
> 
> Other than the usual grouchiness, tendency to be abrasive, and persistence
> in punching holes in every word you say, Yash was a pleasure to meet with.
> Any questions moving forward?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-159083267
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by Perryo** [comment]
Lol @ that description of Yash. I'll look up some stuff when I get home tonight.

**Comment by Perryo** [comment]
@jakepruitt 
Good news! Python has built in functionality for comparing histograms, I don't believe this counts as taking the easy way out as it is a capability of the language and not an included package we used to subvert the requirements. 
Documentation:
http://docs.opencv.org/2.4/modules/imgproc/doc/histograms.html#id1

In our case I think the method we would be using is correlation.

**Comment by SreeniASU** [comment]
I have talked with the TA today on finding the most significant components
of DCT and DWT and as usual he was vague in his answers.

As per the discussion with him, there is no rule of thumb to find the
significant components of DCT or DWT and the method that we following now
might be right or wrong. :-/.

On Mon, Nov 23, 2015 at 7:36 PM, James notifications@github.com wrote:

> @jakepruitt https://github.com/jakepruitt
> Good news! Python has built in functionality for comparing histograms, I
> don't believe this counts as taking the easy way out as it is a capability
> of the language and not an included package we used to subvert the
> requirements.
> Documentation:
> http://docs.opencv.org/2.4/modules/imgproc/doc/histograms.html#id1
> 
> In our case I think the method we would be using is correlation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-159134530
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by SreeniASU** [comment]
One of the problems of identifying significant components as the ones with
the maximum absolute value is that the idea won't work for comparing
different frames. For eg:- For Frame 1, Block (0,0) the significant
components might be at pixel co-ordinates (0,0) and (0,5) whereas for for
Frame 2, Block (0,0) the significant components might be at a different
pixel co-ordinate say (0,0) and (2,3).

Comparison of frames using significant components at different locations
doesn't make sense. So I am modifying the code for block_dct to find the
first n components when arranged in zig-zag order. I discussed it with Prof
Candan as well.

@jakepruitt https://github.com/jakepruitt  : Any comments? For block-dwt
also we need to modify our logic.

On Wed, Nov 25, 2015 at 1:27 PM, Sreenivas Shenoy spsheno1@asu.edu wrote:

> I have talked with the TA today on finding the most significant components
> of DCT and DWT and as usual he was vague in his answers.
> 
> As per the discussion with him, there is no rule of thumb to find the
> significant components of DCT or DWT and the method that we following now
> might be right or wrong. :-/.
> 
> On Mon, Nov 23, 2015 at 7:36 PM, James notifications@github.com wrote:
> 
> > @jakepruitt https://github.com/jakepruitt
> > Good news! Python has built in functionality for comparing histograms, I
> > don't believe this counts as taking the easy way out as it is a capability
> > of the language and not an included package we used to subvert the
> > requirements.
> > Documentation:
> > http://docs.opencv.org/2.4/modules/imgproc/doc/histograms.html#id1
> > 
> > In our case I think the method we would be using is correlation.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-159134530
> > .
> 
> ## 
> 
> Sreenivas P Shenoy
> M.S. Computer Science & Engineering
> Arizona State University,
> spsheno1@asu.edu
> Cell 480-738-3280

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by jakepruitt** [comment]
Awesome, if you could modify the block-dwt code in the same way that would be :ok_hand:. Thanks for doing that @SreeniASU, let me know if you run into any issues.

**Comment by SreeniASU** [comment]
I have already modified it for block_dct and testing it. I will do for
block-dwt as well.

On Wed, Nov 25, 2015 at 3:20 PM, Jake Pruitt notifications@github.com
wrote:

> Awesome, if you could modify the block-dwt code in the same way that would
> be [image: :ok_hand:]. Thanks for doing that @SreeniASU
> https://github.com/SreeniASU, let me know if you run into any issues.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-159744489
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by SreeniASU** [comment]
Done. Please have a look when you get some time.

On Wed, Nov 25, 2015 at 3:23 PM, Sreenivas Shenoy spsheno1@asu.edu wrote:

> I have already modified it for block_dct and testing it. I will do for
> block-dwt as well.
> 
> On Wed, Nov 25, 2015 at 3:20 PM, Jake Pruitt notifications@github.com
> wrote:
> 
> > Awesome, if you could modify the block-dwt code in the same way that
> > would be [image: :ok_hand:]. Thanks for doing that @SreeniASU
> > https://github.com/SreeniASU, let me know if you run into any issues.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/SreeniASU/multimedia-information-systems/issues/30#issuecomment-159744489
> > .
> 
> ## 
> 
> Sreenivas P Shenoy
> M.S. Computer Science & Engineering
> Arizona State University,
> spsheno1@asu.edu
> Cell 480-738-3280

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by jakepruitt** [comment]
Woah, just found a big bug in the quantized compare - it was only comparing the last row of the frames. Making a fix now.
