### ISSUE TITLE
Phase 2 demo

### ISSUE THREAD

**Issue by jakepruitt** [SreeniASU/multimedia-information-systems#31]
Hey @GCrispino @ApertureTS @Perryo @SreeniASU ,

Here are the open times for the demo:

| Day | Time |
| --- | --- |
| Monday | 09:00 AM - 09:45 AM |
| Tuesday | 01:30 PM - 02:15 PM |
| Tuesday | 02:15 PM - 03:00 PM |

I am able to make it on Monday, but have a class during the Tuesday times. If there is a majority on those days, I can skip and make it.

Also, if anyone wants to meet this weekend to get a run down on a demo, let me know. There are a few improvements (to algorithmic encoding time and dynamic quantization) that we could also work on before the demo. Please reply with ideal times and either "We're fine" or "I can work on **[day]**" for part 2.

**Comment by GCrispino** [comment]
I can be there at all the open times. Just let me know which one is better for all of you.

**Comment by ApertureTS** [comment]
I also can be there for any of those times.

**Comment by SreeniASU** [comment]
Tuesday doesn't work for me as I have class from 1:30 PM - 2:45 PM. Monday
9 AM is fine with me

On Wed, Nov 11, 2015 at 6:17 PM, Derek notifications@github.com wrote:

> I also can be there for any of those times.
> On Nov 11, 2015 5:58 PM, "Jake Pruitt" notifications@github.com wrote:
> 
> > Hey @GCrispino https://github.com/GCrispino @ApertureTS
> > https://github.com/ApertureTS @Perryo https://github.com/Perryo
> > @SreeniASU https://github.com/SreeniASU ,
> > 
> > Here are the open times for the demo:
> > Day Time Monday 09:00 AM - 09:45 AM Tuesday 01:30 PM - 02:15 PM Tuesday
> > 02:15
> > PM - 03:00 PM
> > 
> > I am able to make it on Monday, but have a class during the Tuesday
> > times.
> > If there is a majority on those days, I can skip and make it.
> > 
> > Also, if anyone wants to meet this weekend to get a run down on a demo,
> > let me know. There are a few improvements (to algorithmic encoding time
> > and
> > dynamic quantization) that we could also work on before the demo. Please
> > reply with ideal times and either "We're fine" or "I can work on _[day]_"
> > for part 2.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/SreeniASU/multimedia-information-systems/issues/31.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/31#issuecomment-155966613
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by Perryo** [comment]
Any of these times work for me, just let me know what we decide.

**Comment by jakepruitt** [comment]
Went with 09:00 AM - 09:45 AM on Monday 11/16.
