### ISSUE TITLE
Project 3 - Report

### ISSUE THREAD

**Issue by Perryo** [SreeniASU/multimedia-information-systems#39]
@jakepruitt @GCrispino @ApertureTS @SreeniASU 
As you are all aware the project is due tomorrow at midnight. I am going to chat with Jake about part 3, but from what I can see we are pretty much done. I will work on wrapping up the third part of the report for what I worked on as well as Task 1 (a), I ask that each of you do the same.

**Comment by GCrispino** [comment]
@Perryo got it. I have a question. Do you think I can just cite the section where you explain the details of task 1-a when I have to explain something in task 1-d that is implemented in the same way? For example, in both task 1-a and task 1-d we have to slice the frames into 8x8 blocks. On your part of the report regarding to task 1-a, you did a nice diagram illustrating that. So, do you think I would need to repeat that on task 1-d part of the report, or citing that would be fine? 

I was just wondering that repeating it might be redundant, because the implementation is the same in that case.

**Comment by Perryo** [comment]
@GCrispino 
Absolutely, avoid explaining things twice as much as possible. Just say, as discussed in Task 1 (a) the frame is subdivided into 8x8 regions and quantized. Or whatever you need.

**Comment by GCrispino** [comment]
@Perryo ok, got it.

**Comment by jakepruitt** [comment]
@Perryo getting online now, will be diving into the report asap for my parts.

**Comment by GCrispino** [comment]
@jakepruitt @Perryo @ApertureTS @SreeniASU 
Guys, I finished writing the task 1-d part of the report. It is small, but I think I covered it all, because the concept on this part is not too complicated. If you want to take a look at that and see if something is missing, please let me know.

**Comment by jakepruitt** [comment]
Just updated the report with the better results!

**Comment by Perryo** [comment]
@jakepruitt 
Awesome, good find. 
@GCrispino @ApertureTS @SreeniASU 
Looks like the individual portions of the report are done, lets hop on getting the abstract and intro finished and I can reformat and create the submission folder like last time. 

Edit: I will be compiling the 'output' folder for submission, I'll push it to github so we can double check it.

**Comment by Perryo** [comment]
@GCrispino 
Also, it looks like part d is having problems with the write to file function. I'm looking into it, but you might want to check as well.
It looks like you are passing a dictionary with a complex data structure (like that from part a) but are treating it as an array

**Comment by GCrispino** [comment]
@Perryo which problems exactly? When I tested it worked fine.

**Comment by Perryo** [comment]
When attempting to write to file.
![capture](https://cloud.githubusercontent.com/assets/9117438/11461382/779a0a6a-96bf-11e5-9cf6-36286a4dd53c.PNG)

**Comment by GCrispino** [comment]
@Perryo Does it happen every time you try to run this program? Or does it only happen in some situations?

**Comment by Perryo** [comment]
@GCrispino 
Run R2.mp4 with n = 5, shouldnt matter though, breaks for me all the time

**Comment by GCrispino** [comment]
@Perryo what do you mean by running it with frame #150?
I ran it with R2.mp4 and n = 5 and it worked well(using command line arguments). I tried to test it again but python is not working well in my PC sometimes and I can't restart right now(have to finish a test on blackboard). Also, I have not pulled anything from the repository today, did you change something on the code that could be the reason for the errors?

**Comment by jakepruitt** [comment]
@Perryo experiencing the same issue - debugging now.

**Comment by Perryo** [comment]
@GCrispino 
My mistake on the frame #, been looking at part 3 for too long. I haven't changed anything, but if you want to upload that file that was generated from execution that would rock, or send it to me.

**Comment by Perryo** [comment]
@jakepruitt 
Cool, Let me know if you want an extra pair of eyes, I'm hanging around

**Comment by jakepruitt** [comment]
@Perryo pushed a fix to master :+1:

**Comment by Perryo** [comment]
@jakepruitt 
Right on. I'm formatting the report. google docs did _not_ play nice with the images and tables.

**Comment by GCrispino** [comment]
@jakepruitt good job!
@Perryo sorry for the delay. Do you still need the generated file?

**Comment by Perryo** [comment]
@GCrispino 
No worries. I can make it on my own.

**Comment by GCrispino** [comment]
@Perryo ok man.

**Comment by ApertureTS** [comment]
@Perryo I'm done. do you need anything else?

**Comment by Perryo** [comment]
@GCrispino @jakepruitt @ApertureTS @SreeniASU 
The report has all the information filled in, please respond to this indicating that you have nothing more to add, and I will export this to a formatted pdf then upload it for you guys to view.

**Comment by jakepruitt** [comment]
\o/ 27 pages of greatness. So glad we got a head start on this and killed it. Way to go everyone!

**Comment by SreeniASU** [comment]
Good to go I feel!!

On Sun, Nov 29, 2015 at 7:05 PM, Jake Pruitt notifications@github.com
wrote:

> \o/ 27 pages of greatness. So glad we got a head start on this and killed
> it. Way to go everyone!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/39#issuecomment-160497565
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by ApertureTS** [comment]
Thanks for all the work you put into it.

**Comment by jakepruitt** [comment]
Do we need to do peer evaluations for this part?

**Comment by Perryo** [comment]
Yep. Make sure you guys fill those out.

**Comment by Perryo** [comment]
Okay guys, I pushed the report and the submission zip to the Project 3 folder. I'll go ahead an submit this.

**Comment by ApertureTS** [comment]
hey, did we put the work done by each person in the report? I didn't see it

**Comment by ApertureTS** [comment]
also I don't see the conclusion...

**Comment by jakepruitt** [comment]
Shoot, yeah we might need the User Guide and Conclusion. @Perryo should we resubmit it with more information?

**Comment by SreeniASU** [comment]
I am not sure if the Prof really looks into conclusion and all those stuff.
This time we have detailed everything from Task 1 - 3 and I feel that
should be sufficient. But if we really want a conclusion, I can go ahead
and edit it.

On Sun, Nov 29, 2015 at 10:17 PM, Jake Pruitt notifications@github.com
wrote:

> Shoot, yeah we might need the User Guide and Conclusion. @Perryo
> https://github.com/Perryo should we resubmit it with more information?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/39#issuecomment-160517461
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280

**Comment by ApertureTS** [comment]
I know its in the report document. Just figured that it would suck to lose
points for something like that.

**Comment by GCrispino** [comment]
Just so you know, I think on the last phase of the project we didn't put the role of each person on the report, and apparently we didn't lose any points because of it.

**Comment by jakepruitt** [comment]
Updated with Usage and Conclusion, uploaded it at 11 pm with the updates. :rocket:

**Comment by ApertureTS** [comment]
cool

**Comment by jakepruitt** [comment]
Well done team
