### ISSUE TITLE
Understanding of Part1: Correct me if I am wrong.

### ISSUE THREAD

**Issue by SreeniASU** [SreeniASU/multimedia-information-systems#6]
Hi Guys,

This is my understanding of Part1 and based on it I have started writing the code.

1) User inputs : Colorspace (RGB / XYZ/ Lab, YUV etc), A tuple (C0, C1, C2) from the selected colorspace, b = number of bits so that 2^b color instances will be present in our color map

2) We have to create a function such that  for all the values in the range [-1, +1] a suitable tuple value (X,Y,Z) present in the selected color space is mapped to.

3) The mapping is such that -1 will be mapped to (C0,0,0) , 0 will be mapped to (0,C1,0) and +1 will be mapped to (0,0, C2).

4) The function should be continuous, which means for all the values in the range [-1, +1] a mapping is present.

I request everyone to go through these steps and let me know if I am wrong somewhere. I have started coding based on this understanding.

**Comment by jakepruitt** [comment]
> The mapping is such that -1 will be mapped to (C0,0,0) , 0 will be mapped to (0,C1,0) and +1 will be mapped to (0,0, C2)

I think you may be confusing the format of the inputs here. The inputs C0, C1 and C2 are each tuples, so -1 will be mapped to C0, 0 to C1 and +1 to C2. For example, an example input would work the following way:

``` bash
$ python main.py
>>> What colorspace would you like to use? RGB
>>> Please enter the three colors in comma-separated decimal triples:
>>> C0: 10, 200, 45
>>> C1: 50, 255, 255
>>> C2: 0, 0, 0
>>> How many bits should be in the color map? 100
>>> Text file to output the color map to: output.txt
>>> Here is your color map:
>>> [color map here]
```

This, at least, is my understanding. I am not quite sure how the display on the terminal will work, but that may be a function of opencv that I just haven't seen yet.

Does this make sense, @SreeniASU? Also, could you create a pull request with the code you've started? I'll create a PR that asks for the above user inputs.

**Comment by SreeniASU** [comment]
Yes.This makes more sense. I was just confused with the format of the inputs. I have merged your pull request.

**Comment by jakepruitt** [comment]
@SreeniASU - after hearing the clarification in class, I think we should split up this first part into two deliverables so that both of us can work in parallel:
1. **Input to array of colors** - there should be a module/function/class that takes the three initial colors c0, c1, c2, as well as the number of bits b, and outputs an array with length 2^b of colors that will be used in the color map. Each color should be a three-dimensional coordinate, for example, (0, 255, 255). This will mostly just be math/linear algebra.
2. **Array of colors to visual color map** - There should be a second module/function/class that takes the 2^b length array of colors, as well as the color space, and produces the visual representation of the color map in an ASCII text file and in the terminal. This will involve the bulk of OpenCV work.

Which part would you like to take on?

**Comment by SreeniASU** [comment]
Hi Jake,

 I would prefer working more on the first part, if that is ok for you.

Thanks,
Sreenivas

On Tue, Sep 15, 2015 at 11:38 AM, Jake Pruitt notifications@github.com
wrote:

> @SreeniASU https://github.com/SreeniASU - after hearing the
> clarification in class, I think we should split up this first part into two
> deliverables so that both of us can work in parallel:
> 1. _Input to array of colors_ - there should be a
>    module/function/class that takes the three initial colors c0, c1, c2, as
>    well as the number of bits b, and outputs an array with length 2^b of
>    colors that will be used in the color map. Each color should be a
>    three-dimensional coordinate, for example, (0, 255, 255). This will mostly
>    just be math/linear algebra.
> 2. _Array of colors to visual color map_ - There should be a second
>    module/function/class that takes the 2^b length array of colors, as well as
>    the color space, and produces the visual representation of the color map in
>    an ASCII text file and in the terminal. This will involve the bulk of
>    OpenCV work.
> 
> Which part would you like to take on?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SreeniASU/multimedia-information-systems/issues/6#issuecomment-140493776
> .

## 

Sreenivas P Shenoy
M.S. Computer Science & Engineering
Arizona State University,
spsheno1@asu.edu
Cell 480-738-3280
